services:
  nginx:
    container_name: my-nginx-container
    env_file:
      - default.env
    ports:
      - 443:443
    build: requirements/nginx
    init: true
    restart: always
    networks:
      - internal

  mariadb:
    container_name: my-mariadb-container
    env_file:
      - default.env
    ports:
      - 3306:3306
    build: requirements/mariadb
    init: true
    restart: always
    networks:
      - internal
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_PWD: /run/secrets/mariadb_pwd
      MARIADB_ROOT_PWD: /run/secrets/mariadb_root_pwd
    secrets:
      - mariadb_pwd
      - mariadb_root_pwd

  wordpress:
  container_name: my-wordpress-container
  depends_on:
    - mariadb
  env_file:
    - default.env
  ports:
    - 9000:9000
  build: requirements/wordpress
  init: true
  restart: always
  networks:
    - internal
  volumes:
    - wordpress:/var/www/html
  environment:
    MARIADBPWD: /run/secrets/mariadb_pwd
    MARIADBROOTPWD: /run/secrets/mariadb_root_pwd
  secrets:
    - mariadb_pwd
    - mariadb_root_pwd

networks:
  internal:
    driver: bridge

volumes:
  mariadb:
    name: "my-mariadb-volume"
    driver: local
    driver_opts:
      type: none
      device: /home/tzanchi/data/mariadb
      o: bind

  wordpress:
    name: "my-wordpress-volume"

secrets:
  mariadb_pwd:
    file: ./secrets/mariadb/mariadb_pwd.secret
  mariadb_root_pwd:
    file: ./secrets/mariadb/mariadb_root_pwd.secret