services:
  nginx:
    container_name: my-nginx
    depends_on: 
      - wordpress
    env_file:
      - default.env
    ports:
      - 443:443
    image: my-nginx
    build: requirements/nginx
    init: true
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: my-mariadb
    env_file:
      - default.env
    ports:
      - 3306:3306
    image: my-mariadb
    build: requirements/mariadb
    init: true
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      DB_PWD: /run/secrets/mariadb_pwd
      DB_ROOT_PWD: /run/secrets/mariadb_root_pwd
    secrets:
      - mariadb_pwd
      - mariadb_root_pwd

  wordpress:
    container_name: my-wordpress
    depends_on:
      - mariadb
    env_file:
      - default.env
    ports:
      - 9000:9000
    image: my-wordpress
    build: requirements/wordpress
    init: true
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - wordpress:/var/www/html
    environment:
      DB_PWD: /run/secrets/mariadb_pwd
      WP_ADMIN_PWD: /run/secrets/wp_admin_pwd
      WP_USER_PWD: /run/secrets/wp_user_pwd
    secrets:
      - mariadb_pwd
      - wp_admin_pwd
      - wp_user_pwd

networks:
  internal:
    driver: bridge

volumes:
  mariadb:
    name: "DB"
    driver: local
    driver_opts:
      type: none
      device: /home/tzanchi/data/mariadb
      o: bind

  wordpress:
    name: "WordPress"
    driver: local
    driver_opts:
      type: none
      device: /home/tzanchi/data/wordpress
      o: bind

secrets:
  mariadb_pwd:
    file: ./secrets/mariadb/mariadb_pwd.secret
  mariadb_root_pwd:
    file: ./secrets/mariadb/mariadb_root_pwd.secret
  wp_admin_pwd:
    file: ./secrets/wordpress/wp_admin_pwd.secret
  wp_user_pwd:
    file: ./secrets/wordpress/wp_user_pwd.secret
