services:
  nginx:
    container_name: my-nginx-container
    env_file:
      - default.env
    ports:
      - 443:443
    build: requirements/nginx

  mariadb:
    container_name: my-mariadb-container
    ports:
      - 3306:3306
    build: requirements/mariadb

  # wordpress: