services:
  nginx:
    container_name: my-nginx-container
    env_file:
      - default.env
    ports:
      - 443:443
    build: requirements/nginx
    init: true
    networks:
      - internal

  mariadb:
    container_name: my-mariadb-container
    env_file:
      - default.env
    ports:
      - 3306:3306
    build: requirements/mariadb
    init: true
    networks:
      - internal
    volumes:
      - mariadb:/home/tzanchi/data
    environment:
      MARIADB_PWD: /run/secrets/mariadb_pwd
      MARIADB_ROOT_PWD: /run/secrets/mariadb_root_pwd
    secrets:
      - mariadb_pwd
      - mariadb_root_pwd

  # wordpress:

networks:
  internal:
    driver: bridge

volumes:
  mariadb:
    name: "my-mariadb-volume"

  wordpress:
    name: "my-wordpress-volume"

secrets:
  mariadb_pwd:
    file: ./secrets/mariadb_pwd.secret
  mariadb_root_pwd:
    file: ./secrets/mariadb_root_pwd.secret